version: "3"
services: 
    app: 
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes: 
            - "./src:/usr/src"
        # command: /bin/bash
        tty: true
        stdin_open: true