version: '3'
services:
    db:
        build:
            context: .
            dockerfile: "Dockerfile"
        container_name: pg_db
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin