FROM python:3.8

RUN apt update && apt upgrade -y
RUN pip install --upgrade pip
RUN pip install notebook numpy pandas scipy sympy scikit-learn scikit-image matplotlib plotly bs4 selenium chromedriver-binary

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]