version: "3"
services: 
    app: 
        build: 
            context: .
            dockerfile: dockerfile-python
        container_name: app
        ports: 
            - "8888:8888"
        working_dir: /usr/src
        volumes: 
            - ./src:/usr/src